name: "PR Testing"

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
  HONEYCOMB_DATASET: litmus tests
  SERVICE_URL: https://facade-main-6f3kfepqcq-ew.a.run.app/v1/provision

jobs:
  Acceptance:
    runs-on: ubuntu-20.04
    steps:
    - run: |
        set -evx
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/puppetlabs/puppetlabs-testing/actions/runs/${GITHUB_RUN_ID}
